- .changeset/fresh-penguins-heal.md
- .eslintrc.js
- packages/playground/windicss/package.json
- packages/playground/windicss/src/App.svelte
- packages/playground/windicss/vite.config.js
- packages/vite-plugin-svelte/README.md
- packages/vite-plugin-svelte/src/index.ts
- packages/vite-plugin-svelte/src/utils/preprocess.ts
- pnpm-lock.yaml
As discussed with @dominikg.
This solves windicss compatibility problem
> feat: use `sveltePreprocess` options from vite plugins if presents

- .changeset/lemon-toes-relax.md
- packages/vite-plugin-svelte/src/utils/compile.ts
`svelte-hmr` overlay has to go, because it's not visually aligned with Vite's one and, also, it risks creating confusion as to what is happening for end users.
From what I have seen, the two overlays don't really conflict (as in being stacked one over the other), because they don't catch the same type of errors. So, maybe we can reflect on feeding HMR runtime errors to Vite's overlay but, to be honest, that's not something I'm sure about. Mixing build and runtime errors in the same overlay might create even more confusion.
On the opposite, I would be inclined to rework svelte-hmr to reduce the number of try/catch in there, so that errors flow more "normally" (that is, the same way as when there's no HMR machinery) -- at least when overlay is turned off by option. That seems more …
> disable svelte-hmr overlay

- .github/workflows/release.yml
- package.json
- packages/vite-plugin-svelte/package.json
port pnpm caching from ci workflow
use node14
add guard for forks
update release script to call `changeset publish` in hope it does tag and generate proper changelog entries.
> update release action and scripts

- .changeset/dry-cameras-press.md
- packages/playground/ts-type-import/__tests__/ts-type-import.spec.ts
- packages/playground/ts-type-import/index.html
- packages/playground/ts-type-import/package.json
- packages/playground/ts-type-import/src/App.svelte
- packages/playground/ts-type-import/src/index.ts
- packages/playground/ts-type-import/src/lib.ts
- packages/playground/ts-type-import/svelte.config.js
- packages/playground/ts-type-import/tsconfig.json
- packages/playground/ts-type-import/vite.config.js
- packages/vite-plugin-svelte/src/index.ts
- pnpm-lock.yaml
Hello,
I'm trying this plugin on a real-world project and the first thing to say is, it works very well, what a developer experience!
I noticed something that when I enable this plugin on a vite project (even without any svelte files): it breaks a lot of TypeScript modules because it preserve type imports.
Here is a little reproductible scenario:
```typescript
// lib.ts
export interface Test {
arg?: boolean;
}
export function test(): void {
console.log('la');
}
// index.ts
import { test, Test } from './lib';
main();
export function main({ arg = true }: Test = {}): void {
if (arg) test();
}
```
If you compile this app with vite without `@sveltejs/vite-plugin-svelte`, it works as expected, the result would be:
```javascript
function test() {
console.log('la');
}
main();
function main({ arg …
```
> fix: do not preserve type imports (WIP)

- .changeset/sharp-laws-leave.md
- packages/playground/hmr/__tests__/hmr.spec.ts
- packages/vite-plugin-svelte/src/utils/compile.ts
- packages/vite-plugin-svelte/src/utils/options.ts
fixes #9. https://github.com/sveltejs/kit/issues/808 is blocked by this
> respect user `emitCss` option

- packages/vite-plugin-svelte/README.md
Am guilty of knowing this trick, and not announcing this sooner. Alas I pulled the plug :smile: 
Added a section about using `optimizeDeps.exclude`. I know there are plans to remove this caveat soon, but I'm not sure when. In the mean time, it would be great to document this so people don't get frustrated by Svelte's ecosystem.
Feel free to edit the docs!
Note: We could have this info in SvelteKit's FAQ too.
> Add docs on importing third-party Svelte libraries

- .changeset/two-queens-roll.md
- packages/vite-plugin-svelte/src/index.ts
- packages/vite-plugin-svelte/src/utils/load-svelte-config.ts
- packages/vite-plugin-svelte/src/utils/options.ts
> feat: load svelte config file in config hook to update vite config

- .changeset/popular-yaks-fetch.md
- packages/playground/optimizedeps-include/README.md
- packages/playground/optimizedeps-include/index.html
- packages/playground/optimizedeps-include/jsconfig.json
- packages/playground/optimizedeps-include/package.json
- packages/playground/optimizedeps-include/src/App.svelte
- packages/playground/optimizedeps-include/src/main.js
- packages/playground/optimizedeps-include/src/vite-env.d.ts
- packages/playground/optimizedeps-include/vite.config.js
- packages/vite-plugin-svelte/src/index.ts
- packages/vite-plugin-svelte/src/utils/constants.ts
- packages/vite-plugin-svelte/src/utils/options.ts
- pnpm-lock.yaml
> feat: allow svelte imports in optimizeDeps include

- .changeset/breezy-donkeys-argue.md
- packages/vite-plugin-svelte/src/index.ts
- packages/vite-plugin-svelte/src/utils/id.ts
This may be a naive fix so let me know if there are any concerns here.
> fix: don't transform raw imports (fixes #87)

- .changeset/angry-emus-study.md
- .changeset/config.json
- package.json
- pnpm-lock.yaml
- scripts/changelog-github-custom.js
> ci: add custom changelog formatter

- .changeset/cuddly-maps-dance.md
- packages/vite-plugin-svelte/package.json
- pnpm-lock.yaml
to fix dom reordering issue on hmr introduced in svelte 3.38.3
> fix: update svelte-hmr to ^0.14.5 

- .changeset/famous-lemons-draw.md
- packages/vite-plugin-svelte/package.json
- packages/vite-plugin-svelte/src/utils/options.ts
Fixes #10
I initially wanted to import the types from svelte directly for every other files, but eslint keeps complaining of `node/no-missing-import`, and the imports are *ugly* :D So I've only modified the `option.ts` file, which re-exports the types needed. Though, let me know if we do want to import from svelte directly, and we could try that path.
I also removed `--dts-resolve` from `tsup`. It was unable to resolve `estree`, likely from Svelte compiler's dependencies. Removing that doesn't change the final dts however, so it looks safe.
> feat: import svelte types

- .changeset/breezy-kids-divide.md
- packages/vite-plugin-svelte/src/utils/id.ts
Fixes #106 
Not sure of the performance implications, but it seems nice to avoid soon-to-be deprecated APIs.
> chore: replace querystring with URLSearchParams

- packages/vite-plugin-svelte/src/utils/options.ts
removed detailed svelte-hmr interface
removed disableCssHmr 
reexport Warning instead of duplicating
> chore: clean up options interface

- .changeset/nasty-poems-fold.md
- packages/playground/windicss/package.json
- packages/playground/windicss/vite.config.js
- packages/vite-plugin-svelte/package.json
- packages/vite-plugin-svelte/src/utils/__tests__/sourcemap.spec.ts
- packages/vite-plugin-svelte/src/utils/options.ts
- packages/vite-plugin-svelte/src/utils/preprocess.ts
- packages/vite-plugin-svelte/src/utils/sourcemap.ts
- pnpm-lock.yaml
its pretty big at 77kb and only needed for an experimental feature
> fix: turn diff-match-patch into an optional peer dependency

- .changeset/fuzzy-bottles-teach.md
- packages/e2e-tests/configfile-custom/__tests__/configfile-custom.spec.ts
- packages/e2e-tests/configfile-custom/src/App.svelte
- packages/e2e-tests/configfile-custom/src/lib/Child.svelte
- packages/e2e-tests/configfile-custom/vite.config.js
- packages/e2e-tests/configfile-esm/__tests__/configfile-esm.spec.ts
- packages/e2e-tests/configfile-esm/src/App.svelte
- packages/e2e-tests/configfile-esm/src/lib/Child.svelte
- packages/e2e-tests/configfile-esm/vite.config.js
- packages/vite-plugin-svelte/src/utils/options.ts
fixes #113 
maybe vite should resolve root before calling config hook, that information is pretty crucial for plugins to read their own config files.
> fix: resolve vite root before using it (fixes #113)

- .github/workflows/ci.yml
- .github/workflows/release.yml
global store does not vary by node version, so only do it once.
see https://github.com/actions/setup-node/issues/304#issuecomment-886241508
> ci: remove node version from cacheKey for actions/cache

- packages/vite-plugin-svelte/src/index.ts
- packages/vite-plugin-svelte/src/utils/watch.ts
> fix: bypass addWatchFile to avoid dependency issues in vite 2.5

- .github/workflows/ci.yml
- .github/workflows/release.yml
changes
- remove the 3 pnpm store jobs and delegate to setup-node
- join build,lint,audit
- reduce test matrix from 3x3 to 3+1+1
- only run test matrix if build check was successful
num jobs | total  |  concurrent
------------ | ------------- | -------------
before | 15 | 12
after | 6 | 5
> ci: refactor ci workflow to reduce number of jobs

- .changeset/seven-cows-leave.md
- packages/vite-plugin-svelte/src/utils/constants.ts
- packages/vite-plugin-svelte/src/utils/options.ts
by adding svelte itself to optimizeDeps.include by default.
See #125 and related discussions. This change should enhance deduplication of svelte itself.
> fix: improve deduplication support 

- .changeset/fuzzy-mails-brush.md
- packages/e2e-tests/configfile-custom/__tests__/configfile-custom.spec.ts
- packages/e2e-tests/configfile-esm/__tests__/configfile-esm.spec.ts
- packages/e2e-tests/configfile-esm/svelte.config.custom.cjs
- packages/e2e-tests/hmr/__tests__/hmr.spec.ts
- packages/e2e-tests/testUtils.ts
- packages/vite-plugin-svelte/src/utils/load-svelte-config.ts
Fixes #141
Import `.cjs` config file if app is running in `type: module`.
Also added a few more tests for loading different config files.
> fix: use createRequire to require svelte.config.cjs in esm project

- .changeset/four-chairs-rhyme.md
- .eslintrc.js
- packages/e2e-tests/hmr-test-dependency/package.json
- packages/e2e-tests/test-dependency-svelte-field/package.json
- packages/playground/optimizedeps-include/vite.config.js
- packages/vite-plugin-svelte/package.json
- packages/vite-plugin-svelte/src/utils/__tests__/dependencies.spec.ts
- packages/vite-plugin-svelte/src/utils/dependencies.ts
- packages/vite-plugin-svelte/src/utils/log.ts
- packages/vite-plugin-svelte/src/utils/options.ts
- pnpm-lock.yaml
> feat: auto-exclude svelte dependencies in vite.optimizeDeps

- README.md
- docs/config.md
- packages/vite-plugin-svelte/README.md
- packages/vite-plugin-svelte/package.json
- Badges!
- Made the `vite-plugin-svelte` package readme a bit more lively, as that would be shown in npm
- Update `package.json` links
Note: The `package.json`'s `repository.directory` is used to resolve the relative links I used in the `vite-plugin-svelte` package readme, so that npm resolves the link correctly.
> docs: update readme

- .changeset/nine-papayas-confess.md
- .changeset/six-ears-grow.md
- docs/faq.md
- packages/playground/preprocess-with-vite/src/App.svelte
- packages/playground/preprocess-with-vite/src/Bar.svelte
- packages/vite-plugin-svelte/src/utils/log.ts
- packages/vite-plugin-svelte/src/utils/options.ts
Fixes: #153
Transform the exisiting warning with a new warning code: `vite-plugin-svelte-css-no-scopable-elements` and recommend a better path forward.
> fix(hmr): handle compiler warning caused by injected css selector

- .changeset/strange-brooms-crash.md
- packages/vite-plugin-svelte/src/utils/options.ts
This allows users to prevent certain reincludes that could break vite's optimizer, eg `@types/node`
> fix: don't reinclude excluded dependencies in automatic handling

- .changeset/tricky-clouds-grab.md
- packages/e2e-tests/package-json-svelte-field/__tests__/package-json-svelte-field.spec.ts
- packages/e2e-tests/package-json-svelte-field/vite.config.js
- packages/vite-plugin-svelte/src/index.ts
- packages/vite-plugin-svelte/src/utils/dependencies.ts
- packages/vite-plugin-svelte/src/utils/options.ts
Fixes #162
This would prevent `bin`-only packages, `types`-only packages, and esm packages from pre-bundling. Essentially avoiding the issues noted at https://github.com/sveltejs/vite-plugin-svelte/issues/162#issuecomment-912992931
Also thanks to @dominikg that led to this idea!
> fix: only optimize nested cjs dependencies

- .changeset/modern-horses-reply.md
- packages/e2e-tests/_test_dependencies/svelte-api-only/index.js
- packages/e2e-tests/_test_dependencies/svelte-api-only/package.json
- packages/e2e-tests/kit-node/package.json
- packages/e2e-tests/kit-node/src/routes/index.svelte
- packages/e2e-tests/kit-node/svelte.config.js
- packages/vite-plugin-svelte/src/utils/dependencies.ts
- packages/vite-plugin-svelte/src/utils/options.ts
- pnpm-lock.yaml
Fixes https://github.com/sveltejs/kit/issues/2397
Note: I can't really add a failing test since the linked `e2e-test-dep-svelte-api-only` package is automatically `noExternal` by default. I can't force it to external via `config.kit.vite.ssr.external` either since our code respects that (not actually testing the bug). For now, I've tested with the issue's repro https://github.com/Nickersoft/urql-repro and it works.
> fix: add svelte lib without components to noExternal

- .changeset/brave-drinks-look.md
- packages/e2e-tests/kit-node/package.json
- packages/e2e-tests/kit-node/src/routes/index.svelte
- packages/vite-plugin-svelte/src/utils/options.ts
- pnpm-lock.yaml
Fixes #168 
There isn't any reason to add Svelte JS libraries to `ssr.noExternal` in dev mode since `svelte/ssr` isn't handled there too, so this change removes it.
> fix(ssr): simplify noExternal in dev

- .changeset/eleven-frogs-rhyme.md
- packages/vite-plugin-svelte/src/index.ts
- packages/vite-plugin-svelte/src/utils/error.ts
- packages/vite-plugin-svelte/src/utils/esbuild.ts
- packages/vite-plugin-svelte/src/utils/log.ts
convert compiler error to a RollupError that is displayed to the user in a more friendly way than the current stack pointing into vite-plugin-svelte.
This is a bit verbose and causes messages to be sent multiple times on console for sveltekit (ssr and regular compile) but at least it's showing the correct file and frame.
fixes #218
> feat: improve compile error reporting

- .changeset/smooth-rings-run.md
- packages/vite-plugin-svelte/package.json
- packages/vite-plugin-svelte/src/index.ts
- packages/vite-plugin-svelte/src/utils/options.ts
- packages/vite-plugin-svelte/src/utils/watch.ts
instead of fake change event on config file
> refactor: use new server.restart api and update vite peer to ^2.7.0 

- .changeset/clean-rice-fly.md
- packages/vite-plugin-svelte/src/utils/resolve.ts
Fixes the CI issue in https://github.com/sveltejs/kit/pull/3034 where the `node:` protocol was messing with resolving the `svelte` field of package.json. Adding `node-fetch`, Vite's scanner seems to resolve its nested imports using Vite plugin's `resolveId`, and because we're using `enforce: "pre"`, we encounter this scenario before Vite's default resolver, which would've handled this.
I'm also not sure why it's resolving the nested imports, but at the meantime this addition looks fine as well.
> fix: ignore protocol when resolve svelte field

- package.json
- pnpm-lock.yaml
pnpm 6.24.0 now doesn't accept comments in `pnpm.overrides`, which seems fair to me, though now we can't document them, but I don't think it's a big deal.
> ci: fix pnpm install

- packages/vite-plugin-svelte/src/utils/options.ts
This should have `!` based on the previous code. Got lost after the refactor. Otherwise the `enforceOptionsForHmr()` function would make a warning on startup everytime.
I don't think this needs a changeset, since we haven't make a release of the refactor yet?
> fix: create correct default hot options

- .changeset/forty-olives-look.md
- packages/e2e-tests/kit-node/__tests__/kit.spec.ts
- packages/e2e-tests/kit-node/package.json
- packages/e2e-tests/testUtils.ts
- packages/playground/kit-demo-app/package.json
- packages/vite-plugin-svelte/src/utils/options.ts
- packages/vite-plugin-svelte/src/utils/watch.ts
- pnpm-lock.yaml
Closes #210
Tested locally and it seems that it's working fine for SvelteKit on latest version. It probably won't work when someone updates vite-plugin-svelte and not sveltekit, but perhaps it's fine since we're in pre mode.
> feat: auto-restart SvelteKit when Svelte config changed

- .changeset/soft-masks-fold.md
- packages/vite-plugin-svelte/src/utils/preprocess.ts
Add `preserveValueImports: true`, which was a breaking change for esbuild 0.14 where it is [preferred](https://github.com/evanw/esbuild/blob/master/CHANGELOG.md#0140) over `importsNotUsedAsValues: 'preserve'`. I think `importsNotUsedAsValues` can be removed too as they overlap a lot, but keeping as is seems to work fine and backwards-compatible too.
> fix: support `experimental.useVitePreprocess` option for Vite 2.8

- .changeset/rare-crews-give.md
- packages/vite-plugin-svelte/src/index.ts
- packages/vite-plugin-svelte/src/utils/optimizer.ts
- packages/vite-plugin-svelte/src/utils/watch.ts
Resolve `Automatic re-prebundle when svelte config change.` task of #222.
I think this works nicely based on my brief tests. The `preprocessor` field should also be taken care of by converting them into `.toString()`, which is good enough.
> feat: re-prebundle when config changed

- .changeset/popular-tigers-camp.md
- packages/vite-plugin-svelte/src/utils/options.ts
This pull request fixes a [compatibility issue] between `vite-plugin-svelte` and backend integrations like [Vite Ruby], by using the `root` provided by Vite in the `configResolved` hook.
`vite-plugin-svelte` needs to infer the `root` before `configResolved` in order to pre-scan svelte dependencies, which was last changed in #115.
Vite plugins can override options using the `config` hook. In particular, [Vite Ruby](https://github.com/ElMassimo/vite_ruby) changes the `root` option based on user configuration, which is typically a subfolder (instead of the project root, `process.cwd()`).
`vite-plugin-svelte` does not use the resolved value for `root`, which can cause Vite and `vite-plugin-svelte` to use different values of `root` to resolve paths.
Since the `root` is different, the [check …
> fix: use the resolved vite root

- package.json
- pnpm-lock.yaml
Renovate PRs are failing on `pnpm audit`
Note: For some reason, `pnpm audit --fix` decided to add `"node-fetch@<2.6.7": ">=2.6.7"` to `pnpm.overrides`, but running `pnpm i` later doesn't fix the vulnerabilities in the lock file at all, so I modified it a bit. The same fix is applied in `vite-plugin-qrcode`.
> chore: fix vulnerabilities

- .changeset/pretty-hairs-press.md
- packages/vite-plugin-svelte/src/index.ts
- packages/vite-plugin-svelte/src/utils/compile.ts
- packages/vite-plugin-svelte/src/utils/error.ts
- packages/vite-plugin-svelte/src/utils/esbuild.ts
- packages/vite-plugin-svelte/src/utils/log.ts
- packages/vite-plugin-svelte/src/utils/options.ts
see #259 
include stack and filename in errors thrown from svelte.preprocess
This should give people enough information to track it down. new output looks like this
```shell
Error while preprocessing /home/dominikg/develop/sveltejs/vite-plugin-svelte/packages/playground/kit-demo-ts/src/routes/__layout.svelte - Cannot read properties of undefined (reading 'split')
TypeError: Error while preprocessing /home/dominikg/develop/sveltejs/vite-plugin-svelte/packages/playground/kit-demo-ts/src/routes/__layout.svelte - Cannot read properties of undefined (reading 'split')
at Object.parseAttributes (/home/dominikg/develop/sveltejs/vite-plugin-svelte/node_modules/.pnpm/svelte-preprocess@4.9.0_svelte@3.46.2+typescript@4.5.5/node_modules/svelte-preprocess/dist/modules/markup.js:19:10)
at …
```
> fix: preprocess error reporting

- .changeset/chatty-trees-sell.md
- packages/vite-plugin-svelte/src/utils/resolve.ts
i could swear is saw a response in a closed issue that node internals were printed as missing a package.json export in buildEnd.
Can't find that now but we shouldn't even be trying, even if vite is asking our resolve hook.
found it: https://github.com/sveltejs/vite-plugin-svelte/issues/244#issuecomment-1028341898
> fix: don't try to resolve internal node modules via package.json svelte field

- docs/config.md
Adds a bit more detail. It wasn't exactly clear to me what the option did at first. It looks very cool now that I've learned a bit more about it!
> Extend docs for `useVitePreprocess`

- packages/e2e-tests/package-json-svelte-field/__tests__/package-json-svelte-field.spec.ts
- packages/vite-plugin-svelte/src/utils/optimizer.ts
https://github.com/vitejs/vite/pull/6758 updated the prebundling deps to be in `.vite/deps/...`, which will be merged in Vite 2.9.
I also realized with https://github.com/vitejs/vite/pull/6758, the `experimental.prebundleSvelteLibraries` option might not work well as the current flow expects prebundling to happen before server start. Will have to further verify this.
Related discussion on [discord](https://discord.com/channels/804011606160703521/945287098469060708/945293902099923005).
> chore: anticipate vite cache changes

- .changeset/gold-drinks-peel.md
- packages/e2e-tests/_test_dependencies/index-only/index.js
- packages/e2e-tests/_test_dependencies/index-only/package.json
- packages/e2e-tests/_test_dependencies/types-only/index.d.ts
- packages/e2e-tests/_test_dependencies/types-only/package.json
- packages/e2e-tests/dependencies/package.json
- packages/vite-plugin-svelte/src/utils/__tests__/dependencies.spec.ts
- packages/vite-plugin-svelte/src/utils/dependencies.ts
- pnpm-lock.yaml
Fixes #281
`lodash.debounce` exposes the entrypoint via `index.js` implicitly, which is considered CJS to be pre-bundled as well. 
Also added more tests for `needsOptimization()` hueristic.
> fix: optimize nested index-only deps

- .changeset/smooth-bananas-yawn.md
- packages/vite-plugin-svelte/src/index.ts
> fix: prevent errors in resolveViaPackageJsonSvelte breaking vite resolve

- .changeset/cold-pumpkins-enjoy.md
- packages/vite-plugin-svelte/src/index.ts
- packages/vite-plugin-svelte/src/utils/options.ts
see #281 
i'm still getting an error though when adding `bytemd` to a sveltekit project 
this is rendered in the html output of localhost:3000 after a brief flash of an unstyled editor.
```
500
The requested module '/node_modules/.pnpm/codemirror-ssr@0.0.6/node_modules/codemirror-ssr/mode/gfm/gfm.js?v=9e01fcfd' does not provide an export named 'default'
SyntaxError: The requested module '/node_modules/.pnpm/codemirror-ssr@0.0.6/node_modules/codemirror-ssr/mode/gfm/gfm.js?v=9e01fcfd' does not provide an export named 'default'
```
> fix: externalize transitive cjs only deps during dev ssr

- .changeset/thin-swans-talk.md
- packages/playground/kit-demo-app/svelte.config.js
- packages/vite-plugin-svelte/src/utils/preprocess.ts
When using Vite's (experimental) [css.devSourcemap](https://vitejs.dev/config/#css-devsourcemap) feature
The filenames where correct, but the line numbers didn't match.
Changing:
`source: filename`
into
`source: filename?.split(/[/\\]/).pop()`
By changing `source` to only contain the filename instead of the full path fixed the line number issue.
Fixes #300
> fix: Improve css sourcemap accuracy

- docs/config.md
- docs/faq.md
Update docs about the caveats of `prebundleSvelteLibraries`, which should be none now!
> docs: update prebundling caveats

- .changeset/young-chicken-agree.md
- package.json
- pnpm-lock.yaml
Note the Vite peer dep bump in the changeset.
Also updated `pnpm.overrides` for Vite 2.9.1. It should be 2.9.1 from last renovate upgrade but it didn't update the overrides. I'm also wondering now if it's better to bring back the pnpmfile so we don't have to do this manually again.
> chore: update vite peer dep changeset

- .eslintrc.js
- packages/vite-plugin-svelte/src/utils/hash.ts
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> chore: replace deprecated String.prototype.substr()

- .pnpmfile.cjs
- package.json
- pnpm-lock.yaml
Now renovate can update Vite properly
> chore: use pnpmfile to override vite

- .changeset/good-plums-rest.md
- docs/config.md
- packages/e2e-tests/configfile-custom/__tests__/configfile-custom.spec.ts
- packages/e2e-tests/configfile-custom/svelte.config.cjs
- packages/e2e-tests/configfile-custom/svelte.config.custom.cjs
- packages/e2e-tests/configfile-custom/svelte.config.custom.mjs
- packages/e2e-tests/configfile-custom/vite.config.js
- packages/vite-plugin-svelte/src/utils/load-svelte-config.ts
- packages/vite-plugin-svelte/src/utils/options.ts
useful for frameworks like sveltekit that already read the config to avoid doing duplicate work.
> feat: skip reading config file with inline option

- .changeset/silver-readers-wait.md
- .changeset/young-rice-bathe.md
- docs/config.md
- packages/vite-plugin-svelte/src/utils/options.ts
- packages/vite-plugin-svelte/src/utils/watch.ts
to allow sveltekit passing the whole config inline, see https://github.com/sveltejs/kit/pull/4760
> fix: improve support for `configFile: false`  use in kit

- package.json
locally i got pnpm@6.32.11 when executing `pnpm i -g pnpm@6` not sure why, 6.32.12 exists in registry and is tagged as latest-6.
to avoid ci breaking, relax it a bit
> fix: downgrade pnpm engine to ensure ci installs an existing version

- .editorconfig
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .husky/pre-commit
- CONTRIBUTING.md
- package.json
- packages/e2e-tests/e2e-server.js
- packages/e2e-tests/ts-type-import/package.json
- packages/vite-plugin-svelte/package.json
- pnpm-lock.yaml
See more: https://github.com/pnpm/pnpm/releases/tag/v7.0.0
- change `pnpm` engines version to v7
- remove outdated `pnpm` overrides
- update GitHub Actions to run with `pnpm` v7
- update pre-commit hook to use locally installed `lint-staged` rather than `pnpx` one
- change occurrences of "pnpm run" to shorter "pnpm"
- install missing `svelte` peer dependency for `ts-type-import` package
- fix `.editorconfig` configuration to include nested `package.json`
> chore: upgrade to pnpm 7

- .changeset/hot-crabs-reply.md
- packages/vite-plugin-svelte/src/ui/inspector/Inspector.svelte
Chrome triggers a "keydown" event when autocompleting in forms, which triggers a `event.getModifierState is not a function` error.
This change makes sure that only keydown events with a defined key are checked.
Related issue from another GitHub repo: https://github.com/paperjs/paper.js/issues/1398
Screenshot of bug from my project:
> fix(inspector): handle autocomplete keydown event

- .changeset/three-icons-behave.md
- docs/config.md
- packages/vite-plugin-svelte/src/utils/compile.ts
- packages/vite-plugin-svelte/src/utils/options.ts
see https://github.com/sveltejs/vite-plugin-svelte/issues/345#issuecomment-1138428492
this does not apply to dynamicCompileOptions so that remains  an escape-hatch for the brave.
> fix: Remove user-set values for essential compilerOptions and log a warning

- .changeset/breezy-tigers-hang.md
- packages/vite-plugin-svelte/package.json
- pnpm-lock.yaml
just so we can remove the `hot.optimistic: false` override in https://github.com/sveltejs/kit/pull/5108
> bump svelte-hmr version

- .changeset/stupid-melons-try.md
- packages/vite-plugin-svelte/src/utils/dependencies.ts
this removes a confusing error log but doesn't fix the underlying issue which is in vite itself. see #362
> fix: ignore __vite-browser-external when trying to resolve svelte packages

- .changeset/five-dogs-care.md
- packages/e2e-tests/kit-node/package.json
- packages/vite-plugin-svelte/package.json
- packages/vite-plugin-svelte/src/utils/options.ts
- pnpm-lock.yaml
This isn't really testable until kit stops passing `configFile: false` in inline options.
Manually ignoring that flag and removing the inline kit options show it works though.
> feat: automatic handling for kit.browser.hydrate config

- docs/config.md
- docs/faq.md
> docs: clarify cssHash in dev

- .changeset/rich-pianos-fly.md
- docs/config.md
- packages/vite-plugin-svelte/src/handle-hot-update.ts
- packages/vite-plugin-svelte/src/index.ts
- packages/vite-plugin-svelte/src/utils/log.ts
- packages/vite-plugin-svelte/src/utils/options.ts
totally experimental and untested. Primarily for feedback and discussion at this point
> feat: add option to send warnings to dev client via websocket

- .changeset/healthy-worms-double.md
- docs/config.md
- packages/e2e-tests/configfile-custom/svelte.config.custom.cjs
- packages/e2e-tests/configfile-custom/svelte.config.custom.mjs
- packages/e2e-tests/hmr/__tests__/hmr.spec.ts
- packages/e2e-tests/inspector-kit/svelte.config.js
- packages/vite-plugin-svelte/src/index.ts
- packages/vite-plugin-svelte/src/utils/load-svelte-config.ts
- packages/vite-plugin-svelte/src/utils/options.ts
To avoid problems with future name clashes we introduce `vitePlugin` namespace in svelte.config.js.
svelte options that are of global interest, eg `compilerOptions`, `preprocess` and `extensions` remain in the config root.
All other options mentioned in https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#plugin-options are moved.
Additional validation/errors have been introduced to avoid invalid options and inform the user.
> refactor: move plugin options to "vitePlugin" in svelte.config.js

- .npmrc
> chore: remove the loglevel=warning setting now that action setup-node is fixed

- docs/config.md
Hi... I find the URL to svelte compile options documentation is invalid. Just updated the URL.
> docs: update svelte compile options URL

- .changeset/polite-seas-rule.md
- packages/vite-plugin-svelte/src/ui/inspector/Inspector.svelte
they happen eg when using paste from rightclick context menu. 
The inspector only cares about pressed keys though to determine combo use, so it is safe to ignore events that do not have a key set.
> fix: avoid runtime error by ignoring keyless keyup events

- .changeset/short-clocks-flow.md
- packages/vite-plugin-svelte/src/ui/inspector/plugin.ts
- packages/vite-plugin-svelte/src/ui/inspector/utils.ts
- packages/vite-plugin-svelte/src/utils/options.ts
- pnpm-lock.yaml
> fix: inspector read file for vite 3.1

- .changeset/fair-dodos-dance.md
- .changeset/light-readers-leave.md
- docs/config.md
- packages/playground/kit-demo-app/svelte.config.js
- packages/vite-plugin-svelte/src/ui/inspector/Inspector.svelte
- packages/vite-plugin-svelte/src/ui/inspector/plugin.ts
- packages/vite-plugin-svelte/src/utils/options.ts
fixes #435 
needs documentation, but where?
svelte-inspector is going to be extracted into a separate package in this monorepo to enable code-sharing with the editor plugin that was demoed on svelte-summit.
@lukaszpolowczyk  i hope you are fine with ArrowUp/Down, that seems more fitting than +/-.
> feat: add drilling and tag display to inspector

- packages/e2e-tests/hmr/__tests__/hmr.spec.ts
- packages/e2e-tests/hmr/src/components/partial-hmr/PartialHmr.svelte
- packages/e2e-tests/hmr/src/components/partial-hmr/UsingNamed.svelte
- packages/e2e-tests/hmr/src/components/partial-hmr/UsingOnlyDefault.svelte
Adding these assertions ensure that the test is not passing by updating too eagerly. For example, with old svelte-hmr option `acceptNamedExports:false`, the current test would pass, but the hardened version would not.
We only want the actual consumers of the named exports to be impacted by the HMR bubble. Consumers of only the default export (i.e. the component) should not be impacted, because the default export is accepted by the component itself.
> test: harden partialAccept test

- .changeset/little-ligers-look.md
- packages/e2e-tests/hmr/__tests__/hmr.spec.ts
- packages/e2e-tests/hmr/src/App.svelte
- packages/e2e-tests/hmr/src/components/partial-hmr/ModuleContext.svelte
- packages/e2e-tests/hmr/src/components/partial-hmr/PartialHmr.svelte
- packages/e2e-tests/hmr/src/components/partial-hmr/UsingNamed.svelte
- packages/e2e-tests/hmr/src/components/partial-hmr/UsingOnlyDefault.svelte
- packages/e2e-tests/testUtils.ts
- packages/playground/kit-demo-app/src/routes/about/+page.js
- packages/vite-plugin-svelte/package.json
- packages/vite-plugin-svelte/src/utils/options.ts
- pnpm-lock.yaml
to allow context=module updates, see issue #134
This is enabled by default, but can be disabled by either  
`hot:{partialAccept: false}` in vite-plugin-svelte options or
`experimental: {hmrPartialAccept: false}` in vite config.
> fix: update svelte-hmr and enable partial accept

- .changeset/fair-dodos-dance.md
- .changeset/friendly-avocados-tie.md
- .changeset/light-readers-leave.md
- .changeset/pretty-boxes-fail.md
- docs/config.md
- packages/vite-plugin-svelte/src/ui/inspector/Inspector.svelte
- packages/vite-plugin-svelte/src/ui/inspector/plugin.ts
- packages/vite-plugin-svelte/src/utils/options.ts
this PR follows up on #436 to complete keyboard only navigation and a11y improvements
cc @geoffrich
> feat: add keyboard navigation to svelte inspector and improve a11y

- .changeset/eighty-dingos-dance.md
- .changeset/mighty-tigers-sell.md
- packages/vite-plugin-svelte/src/ui/inspector/Inspector.svelte
> Fix: inspector bugs

- .changeset/cuddly-tools-fold.md
- packages/vite-plugin-svelte/src/utils/preprocess.ts
Similar as https://github.com/vitejs/vite/pull/10207, use `esnext` so we don't lower the syntax, as we only want to transpile ts -> js.
> fix: use esnext for useVitePreprocess

- .changeset/ninety-pans-wave.md
- packages/vite-plugin-svelte/package.json
- packages/vite-plugin-svelte/src/utils/id.ts
- pnpm-lock.yaml
Import `createFilter` from `vite` instead (available since Vite 3).
This should autoclose #468
> refactor: remove `@rollup/pluginutils` dependency

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
1) bug reports are for bugs only and 
2) a reproduction is absolutely required
removed the severity dropdown as that hasn''t been used correctly by some reporters in the past.
If we want to categorize issues by that, we can add labels later
> chore: update issue templates to make it more clear that 

- .changeset/twelve-islands-jump.md
- docs/config.md
- docs/faq.md
- packages/vite-plugin-svelte/src/index.ts
- packages/vite-plugin-svelte/src/utils/options.ts
Hurray!
We can address https://github.com/sveltejs/vite-plugin-svelte/issues/421 in a follow-up since it only makes prebundling less effective, but doesn't break any projects
> feat: bring `prebundleSvelteLibraries` out of experimental

- .changeset/shaggy-panthers-leave.md
- packages/vite-plugin-svelte/package.json
Add missing "types" definition to the exports object. In some cases the one defined at the root level of the package json file is ignored if exports is also defined.
Usecase:
I have a package (type module) where I export preconfigured vite configs and I use this plugin in one of them. Pre-processing the configs using vite and vite-plugin-dts reports this error:
```sh
[vite:dts] Start generate declaration files...
src/configs/app-svelte-vite.config.ts:1:24 - error TS7016: Could not find a declaration file for module '@sveltejs/vite-plugin-svelte'. '/home/alex/git/js/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.1.0_svelte@3.52.0+vite@3.2.3/node_modules/@sveltejs/vite-plugin-svelte/dist/index.cjs' implicitly has an 'any' type.
Try `npm i --save-dev @types/sveltejs__vite-plugin-svelte` …
```
> Add types to the exports

- packages/vite-plugin-svelte/src/utils/__tests__/svelte-version.spec.ts
- packages/vite-plugin-svelte/src/utils/esbuild.ts
- packages/vite-plugin-svelte/src/utils/svelte-version.ts
#490 introduced svelte version testing that didn't work as desired. inverted the condition and also updated the value used by esbuild plugin to inject css.
> fix: svelte version detection was broken

- .changeset/flat-shrimps-return.md
- packages/vite-plugin-svelte/src/utils/options.ts
to initialize compilerOptiona.hydratable
> fix: no longer read kit.browser.hydrate

- .github/renovate.json5
prevent pnpm engine requirement from going past codeflow deployed version
> chore: disable renovate engines bump to 

- .changeset/curly-readers-invite.md
- packages/e2e-tests/_test_dependencies/svelte-exports-simple/index.js
- packages/e2e-tests/_test_dependencies/svelte-exports-simple/package.json
- packages/e2e-tests/_test_dependencies/svelte-exports-simple/src/components/Dependency.svelte
- packages/e2e-tests/prebundle-svelte-deps/__tests__/prebundle-svelte-deps.spec.ts
- packages/e2e-tests/prebundle-svelte-deps/package.json
- packages/e2e-tests/prebundle-svelte-deps/src/App.svelte
- packages/e2e-tests/resolve-exports-svelte/__tests__/resolve-exports-svelte.spec.ts
- packages/e2e-tests/resolve-exports-svelte/index.html
- packages/e2e-tests/resolve-exports-svelte/package.json
- packages/e2e-tests/resolve-exports-svelte/src/App.svelte
- packages/e2e-tests/resolve-exports-svelte/src/main.js
- packages/e2e-tests/resolve-exports-svelte/src/vite-env.d.ts
- packages/e2e-tests/resolve-exports-svelte/vite.config.js
- packages/vite-plugin-svelte/src/utils/constants.ts
- packages/vite-plugin-svelte/src/utils/options.ts
- pnpm-lock.yaml
This PR enables using an export condition `svelte` to point at svelte source files.
eg this exports map
```js
"exports": {
"./*": {
"svelte": "./src/components/*"
},
".": {
"svelte": "./index.js"
}
}
```
allows you to either `import {SomeThing} from 'some-lib'` when index.js exports SomeThing, or `import SomeThing from 'some-lib/SomeThing.svelte'`  if you prefer a deep import to avoid the index.
This is a very simplistic example and the real usecase is to still allow exporting compiled svelte files or other js files via the import condition.
See https://nodejs.org/api/packages.html#conditional-exports for what you can do with export conditions.
> feat: enable support for exports condition

- .changeset/dry-seahorses-sin.md
- packages/vite-plugin-svelte/package.json
- packages/vite-plugin-svelte/src/utils/vite-plugin-svelte-stats.ts
- pnpm-lock.yaml
catch errors to avoid breaking the process just because stats didn't work
> fix: use a recursive helper to find named parent package

- .changeset/chilly-maps-talk.md
- packages/vite-plugin-svelte/package.json
- pnpm-lock.yaml
vitefu 0.2.2 still peers with vite 3, and some package managers don't auto-update leading to peer dependency warnings.
bump to 0.2.3 so their hand is forced
> fix: bump vitefu

- .changeset/small-oranges-give.md
- packages/vite-plugin-svelte/src/handle-hot-update.ts
- packages/vite-plugin-svelte/src/index.ts
> fix: convert compile error on hmr

- packages/playground/big/package.json
- packages/playground/big/vite.config.js
- packages/playground/windicss/package.json
- packages/playground/windicss/vite.config.js
Convert `vite.config.js` to ESM so they can be run.
> chore: update cjs vite config to esm

- .changeset/serious-sloths-grab.md
- packages/e2e-tests/preprocess-with-vite/__tests__/preprocess-with-vite.spec.ts
- packages/e2e-tests/preprocess-with-vite/src/Foo.svelte
- packages/vite-plugin-svelte/src/utils/__tests__/compile.spec.ts
- packages/vite-plugin-svelte/src/utils/compile.ts
see https://github.com/sveltejs/kit/issues/9492
This is a workaround, the actual cause is the svelte compiler moving inline pure annotation comments to the end of a line, so that the subsequent bundling step associates them with a different node, possibly causing code to be removed that should have been preserved or otherwise altering the build output.
`/* @__PURE__ */` comments that are at the end of a line are being replaced with the same amount of spaces so that character count/sourcemaps remain unaffected.
> fix(vitePreprocess): remove dangling pure annotations

- packages/vite-plugin-svelte/src/utils/log.ts
- packages/vite-plugin-svelte/src/utils/options.ts
more generic version for namespaced log/debug, including an improved check if the stats namespace has been enabled by the user
> refactor: use generic namespace for logging instead of hardcoded stats

- packages/playground/kit-demo-app/src/routes/sverdle/+page.svelte
And these warnings end up as yellow check boxes on test action runs.
> chore: remove aria-selected attribute from button as it causes warnings

- .changeset/chilled-tigers-flash.md
- packages/vite-plugin-svelte/src/index.ts
[according to @dominikg](https://github.com/sveltejs/svelte/pull/8497#issuecomment-1506354874):
> latest vite does not need the custom resolve for it in v-p-s anymore, but early vite 4 versions did
I think we can safely remove this. People who are on old versions of Vite 4 may get larger apps if they upgrade `vite-plugin-svelte` without upgrading Vite, but that's relatively safe as nothing will break.
There's some nice benefits to removing this including simplifying the `vite-plugin-svelte` code and eventually paving the way for us to stop exporting `svelte/ssr` in Svelte core
> Skip Vite resolve workaround on Vite 4.1+ or Svelte 4+

- .changeset/smooth-llamas-reflect.md
- docs/config.md
- packages/e2e-tests/inspector-kit/__tests__/inspector.kit.spec.ts
- packages/vite-plugin-svelte/src/ui/inspector/plugin.ts
- packages/vite-plugin-svelte/src/utils/options.ts
Per changeset:
Remove internal SvelteKit specific handling
- Disallow `kit` prop in inline options
- Remove default `hydratable: true` option for SvelteKit
- Inspector code mounts on `/@vite/client` to be framework agnostic
Re no1, I'm not sure how we're using that today, but seems safe to me to remove the runtime validation for it.
Re no2, SvelteKit has set it by itself for quite a while now: https://github.com/sveltejs/kit/blob/fb68c253a59402df2b2b1b5db7a54fad504cdd32/packages/kit/src/exports/vite/index.js#L136
Re no3, this removes the need for the `inspector.appendTo` option so we don't need kit specific handling for it. Makes way for https://github.com/sveltejs/vite-plugin-svelte/pull/631
> feat: remove SvelteKit specific handling

- .changeset/bright-fans-count.md
- .changeset/cold-tips-lay.md
- .changeset/fluffy-monkeys-boil.md
- .changeset/funny-suits-grin.md
- .changeset/green-rats-cry.md
- .changeset/orange-lobsters-cross.md
- .changeset/perfect-nails-rescue.md
- .changeset/weak-crabs-type.md
- docs/config.md
- packages/e2e-tests/css-dev-sourcemap/__tests__/css-dev-sourcemap.spec.ts
- packages/vite-plugin-svelte/src/index.ts
- packages/vite-plugin-svelte/src/ui/inspector/Inspector.svelte
- packages/vite-plugin-svelte/src/ui/inspector/load-inspector.js
- packages/vite-plugin-svelte/src/ui/inspector/options.ts
- packages/vite-plugin-svelte/src/ui/inspector/plugin.ts
- packages/vite-plugin-svelte/src/utils/options.ts
We have received some Feedback for svelte-inspector and this PR aims to address most of it.
fixes #434  by moving inspector ui outside of `<body>`
fixes #518  by automatically disabling inspector when user leaves the browser window after opening a file
fixes #551  by prepending configured base path to __openInEditor request
fixes #555  by changing default combo on linux to control-shift
fixes #559  by enabling holdMode by default
```shell
SVELTE_INSPECTOR_TOGGLE=control-shift
SVELTE_INSPECTOR_OPTIONS='{"holdMode": false}'
```
Move your inspector config to the root of `vitePlugin`.
```diff
// svelte.config.js
export default {
vitePlugin:{
experimental:{
-      inspector: {...}
},
+   inspector: {...}
}
}
```
> feat: svelte inspector updates and promote from experimental

- packages/vite-plugin-svelte/src/handle-hot-update.ts
- packages/vite-plugin-svelte/src/index.d.ts
- packages/vite-plugin-svelte/src/index.ts
- packages/vite-plugin-svelte/src/preprocess.ts
- packages/vite-plugin-svelte/src/types/compile.d.ts
- packages/vite-plugin-svelte/src/types/dependencies.d.ts
- packages/vite-plugin-svelte/src/types/esbuild.d.ts
- packages/vite-plugin-svelte/src/types/options.d.ts
- packages/vite-plugin-svelte/src/types/preprocess.d.ts
- packages/vite-plugin-svelte/src/types/sourcemaps.d.ts
- packages/vite-plugin-svelte/src/types/vite-plugin-svelte-cache.d.ts
- packages/vite-plugin-svelte/src/types/vite-plugin-svelte-stats.d.ts
- packages/vite-plugin-svelte/src/utils/compile.ts
- packages/vite-plugin-svelte/src/utils/dependencies.ts
- packages/vite-plugin-svelte/src/utils/error.ts
- packages/vite-plugin-svelte/src/utils/esbuild.ts
- packages/vite-plugin-svelte/src/utils/hash.ts
- packages/vite-plugin-svelte/src/utils/id.ts
- packages/vite-plugin-svelte/src/utils/load-svelte-config.ts
- packages/vite-plugin-svelte/src/utils/log.ts
- packages/vite-plugin-svelte/src/utils/optimizer.ts
- packages/vite-plugin-svelte/src/utils/options.ts
- packages/vite-plugin-svelte/src/utils/preprocess.ts
- packages/vite-plugin-svelte/src/utils/resolve.ts
- packages/vite-plugin-svelte/src/utils/sourcemaps.ts
- packages/vite-plugin-svelte/src/utils/svelte-version.ts
- packages/vite-plugin-svelte/src/utils/vite-plugin-svelte-cache.ts
- packages/vite-plugin-svelte/src/utils/vite-plugin-svelte-stats.ts
- packages/vite-plugin-svelte/src/utils/watch.ts
some jsdocs nits:
- space things up
- use `[paramName]` instead of `{type=}` for optional params
- use `@typedef` for one-off types in a file
- fix jsdoc typecast not working in vscode
> refactor: update jsdoc syntax

- .changeset/long-dodos-report.md
- packages/vite-plugin-svelte/src/utils/compile.js
depends on https://github.com/sveltejs/svelte/pull/8719 getting merged for Svelte 4
> fix: remove pure comments only for Svelte 3

- docs/advanced-usage.md
I got an error when trying to use the import from the docs:
```
Unexpected token g in JSON at position 1
```
This PR fixes the example.
> [docs]: fix `compilerOptions` exampe

- .changeset/dirty-carrots-clap.md
- packages/vite-plugin-svelte/src/utils/constants.js
it's used internally by svelte4, but vite dynamically discovering it leads to
```
9:33:40 PM [vite] ✨ new dependencies optimized: svelte/internal/disclose-version
9:33:40 PM [vite] ✨ optimized dependencies changed. reloading
```
so add it to our internal list thats used to generate optimizeDeps.include
> fix: add svelte/internal/disclose-version  to optimizeDeps.include

- .changeset/six-cherries-hear.md
- packages/e2e-tests/_test_dependencies/vite-plugins/index.js
- packages/e2e-tests/kit-node/__tests__/kit.spec.ts
- packages/e2e-tests/kit-node/package.json
- packages/e2e-tests/kit-node/vite.config.js
- packages/vite-plugin-svelte/src/utils/dependencies.js
- pnpm-lock.yaml
fixes #710 
our vitefu setup detected `@sveltejs/package` as a library that uses svelte because of it's peer dep on svelte. But in this case it isn't used when building the actual application, so we have to ignore it here.
> fix: ignore @sveltejs/package and svelte2tsx for generated vite config

- .changeset/few-eagles-turn.md
- packages/vite-plugin-svelte-inspector/src/runtime/Inspector.svelte
> fix(inspector): disable while combo is held when extra key are pressed or leaving browser

- .changeset/config.json
- package.json
- packages/vite-plugin-svelte/package.json
- pnpm-lock.yaml
use updateInternalDependencies:  'minor' and hide  the "workspace:^" selector from changesets by applying it in an override.
> chore(changesets): prevent bumping inspector dependency on patches

- .eslintrc.js
- packages/e2e-tests/e2e-server.js
- packages/e2e-tests/hmr/src/components/partial-hmr/ModuleContext.svelte
- packages/e2e-tests/prebundle-svelte-deps/src/App.svelte
- packages/e2e-tests/preprocess-with-vite/src/Foo.svelte
- packages/e2e-tests/ts-type-import/src/App.svelte
- packages/e2e-tests/vite-ssr-esm/src/components/Foo.svelte
- packages/e2e-tests/vite-ssr/src/components/Foo.svelte
- packages/playground/optimizedeps-include/vite.config.js
- packages/vite-plugin-svelte/src/types/compile.d.ts
I found one more rule we have in `@sveltejs/eslint-config` that's missing here. I tried to just apply that package as a base config here, but it was too complicated - there's a lot of stuff that's different about this repo like CJS examples, linting of markdown, etc. that we don't have in the other repos at the moment
> chore: prefer const

- .changeset/big-items-shave.md
- .github/workflows/ci.yml
- .github/workflows/release.yml
- package.json
- packages/vite-plugin-svelte-inspector/package.json
- packages/vite-plugin-svelte/package.json
node16 is end of life and vite5 also requires node18.
fixes #722
> breaking: remove support for 14 and 16

- packages/vite-plugin-svelte-inspector/package.json
- packages/vite-plugin-svelte/package.json
we had them on regular ranges to avoid changesets creating extra versions, but now we have to rely on it to set the initial change correctly
> fix: use workspace selector on internal peer deps

- .changeset/grumpy-emus-destroy.md
- packages/vite-plugin-svelte/src/preprocess.js
- packages/vite-plugin-svelte/src/utils/compile.js
- packages/vite-plugin-svelte/src/utils/error.js
- packages/vite-plugin-svelte/src/utils/preprocess.js
Fix https://github.com/sveltejs/vite-plugin-svelte/issues/585
Also added names for our preprocessors. Not very fond that we now have a lot of logic for error handling, but probably still good for users in the long run (as long as the logic itself dont cause more errors)
> feat: improve compile error

- .changeset/nasty-queens-beam.md
- .prettierrc.js
- docs/config.md
- packages/e2e-tests/dynamic-compile-options/__tests__/dynamic-compile-options.spec.ts
- packages/e2e-tests/dynamic-compile-options/index.html
- packages/e2e-tests/dynamic-compile-options/package.json
- packages/e2e-tests/dynamic-compile-options/src/App.svelte
- packages/e2e-tests/dynamic-compile-options/src/components/A.svelte
- packages/e2e-tests/dynamic-compile-options/src/components/B.svelte
- packages/e2e-tests/dynamic-compile-options/src/main.js
- packages/e2e-tests/dynamic-compile-options/vite.config.js
- packages/vite-plugin-svelte/src/index.d.ts
- packages/vite-plugin-svelte/src/utils/compile.js
- packages/vite-plugin-svelte/src/utils/esbuild.js
- packages/vite-plugin-svelte/src/utils/options.js
- pnpm-lock.yaml
The option has been there for a while and is used. Promote it to proper with version 3.0.
Technically not a breaking change as we copy it over and log a warning.
> feat: promote experimental.dynamicCompileOptions

- .changeset/funny-waves-poke.md
- packages/vite-plugin-svelte/src/utils/compile.js
- packages/vite-plugin-svelte/src/utils/preprocess.js
this is usually a sign for a bad setup/import, see #763 
all these files have to be read separately and changing one of them leads to a hot reload of the component. Depending on a few files is ok, but many cause issues.
Messages get added as extra compiler warnings using the `vite-plugin-svelte-preprocess-` prefix. This way users can opt to ignore them via `onwarn` hook. 
Are these checks too rigid and do we need FAQ entries and link them in the messages?
> feat(preprocess): check preprocess dependencies for anomalies

- packages/vite-plugin-svelte-inspector/package.json
- packages/vite-plugin-svelte/package.json
to avoid changesets cross bumping all the time
> chore: revert to regular version selectors 

- packages/vite-plugin-svelte/__tests__/preprocess.spec.js
- packages/vite-plugin-svelte/package.json
- packages/vite-plugin-svelte/src/utils/load-svelte-config.js
- pnpm-lock.yaml
- Install `sass` in `packages/vite-plugin-svelte` so the `vitePreprocess` unit test is able to import `sass`
- Add `inlineConfig` in `vitePreprocess` unit test so it has a proper `root` to resolve `sass`
- Refactor dynamic import hack to normal import
- I'm not really sure why, but ever since https://github.com/vitejs/vite/pull/14544 it causes Vitest to error with:
```bash
FAIL  packages/e2e-tests/import-queries/__tests__/import-queries.spec.ts > ssrLoadModule
TypeError: A dynamic import callback was not specified.
❯ eval packages/vite-plugin-svelte/src/utils/load-svelte-config.js:22:30
20| // see https://github.com/microsoft/TypeScript/issues/43329#issuecomment-811606238
21| // also use timestamp query to avoid caching on reload
22| const dynamicImportDefault = new Function(
| …
```
> chore: fix test run when linking vite

- .changeset/wet-drinks-call.md
- packages/vite-plugin-svelte/src/handle-hot-update.js
This message isn't immediately actionable for developers and can reasonably be considered debugging output. Therefore, the log level has been updated to reflect this.
This fixes #803.
> Lowers log level to debug

- .changeset/eighty-oranges-brush.md
- packages/vite-plugin-svelte/src/utils/compile.js
- packages/vite-plugin-svelte/src/utils/error.js
see #796 
not a fan of the complexity in these regexes or the fact that we copy them.
For the script lang regex in compile.js we could think about using a spy preprocessor to get the attribute value.
For the error messages, should this be something svelte itself emits so that other tools also benefit?
> fix: use improved regex for script and style from svelte

- packages/e2e-tests/kit-node/__tests__/kit.spec.ts
- packages/vite-plugin-svelte/src/utils/constants.js
Fixes https://github.com/sveltejs/vite-plugin-svelte/issues/808
> fix: add browser to default resolve.mainFields

- .changeset/eleven-wombats-begin.md
- packages/vite-plugin-svelte/src/utils/compile.js
...when detecting script language
Related to https://github.com/sveltejs/language-tools/issues/2204
Let me know if there's any other place where this needs a fix
> fix: handle closing tags in attributes

- docs/faq.md
> docs: fix markdown in faq.md

- package.json
- packages/e2e-tests/_test_dependencies/svelte-hybrid/package.json
- packages/e2e-tests/inspector-kit/package.json
- packages/e2e-tests/kit-node/package.json
- packages/e2e-tests/ts-type-import/package.json
- packages/playground/big-component-library-kit/package.json
- packages/playground/kit-demo-app/package.json
- packages/playground/kit-demo-app/src/routes/sverdle/+page.server.js
- packages/vite-plugin-svelte/package.json
- pnpm-lock.yaml
- close #825 
- close #826 
- close #829
> chore: update to SvelteKit 2

- packages/e2e-tests/import-queries/__tests__/import-queries.spec.ts
to accept both application/javascript and text/javascript response from devserver
see https://github.com/vitejs/vite/pull/15427
> fix(test): relax js mime type test 

- .changeset/rare-buttons-argue.md
- packages/vite-plugin-svelte/__tests__/compile.spec.js
- packages/vite-plugin-svelte/src/utils/compile.js
- packages/vite-plugin-svelte/src/utils/error.js
The script regex introduced in c2017e0 matches comment blocks by mistake. This causes files using a header comment tag to always be detected as `js`.  This will produce an error if the script tag imports a module with an explicit `.js` extensions, where physically only a `.ts` file is present.
This PR removes the comment matching part of the two regex instances and introduces a test to verify the script language gets properly detected in the presence of a header comment block.
```svelte
<script lang="ts">
// the following will cause Failed to resolve import "./foo.js" from "src/*.svelte". Does the file exist?
// if physically the file's name is `foo.ts`
import { foo } from './foo.js';
</script>
```
> fix: correctly detect script language during compilation

- .eslintrc.cjs
for some reason changesets decided to reformat it and i don't want to have to fight it.
> fix: ignore changelog in lint

- packages/e2e-tests/inspector-kit/package.json
- packages/e2e-tests/kit-node/package.json
- packages/playground/big-component-library-kit/package.json
- packages/playground/kit-demo-app/package.json
- pnpm-lock.yaml
These fix security vulnerabilities, even if they don't affect our e2e tests we want them, and dependabot :robot:  complains too
> chore(deps): update kit and adapter-node

- packages/vite-plugin-svelte/package.json
Otherwise this can cause issues with changesets generating useless extra entries and it also fails svelte-ecosystem-ci  https://github.com/sveltejs/svelte-ecosystem-ci/actions/runs/7751646929/job/21139884659
> chore(deps): revert using workspace:^ selector for svelte-inspector to actual version

- .changeset/late-pans-guess.md
- packages/vite-plugin-svelte/src/utils/compile.js
- packages/vite-plugin-svelte/src/utils/load-raw.js
`enableSourcemap` for styles was disabled in SSR due to a caveat with Vite <5 static env replacement, but since Vite 5, we don't have to workaround that anymore. So the `enableSourcemap` setting for it can be removed. Tests were added in https://github.com/sveltejs/vite-plugin-svelte/pull/201. In practice, this shouldn't incur a perf hit.
We also use `enableSourcemap` in another place - the advanced queries. Since Svelte 5, the option was deprecated:
```
The enableSourcemap option has been removed. Source maps are always generated now, and tooling can choose to ignore them.
```
So I disabled it for Svelte 5. We could also completely remove in for Svelte 4, but I didn't want to change too much.
> Remove unnecessary enableSourcemap usage

- .changeset/popular-islands-remain.md
- packages/e2e-tests/configfile-custom/src/main.js
- packages/e2e-tests/configfile-esm/src/main.js
- packages/e2e-tests/css-dev-sourcemap/src/main.js
- packages/e2e-tests/custom-extensions/src/main.js
- packages/e2e-tests/dynamic-compile-options/src/main.js
- packages/e2e-tests/env/src/main.js
- packages/e2e-tests/hmr/src/index.js
- packages/e2e-tests/import-queries/src/main.js
- packages/e2e-tests/inspector-vite/src/main.js
- packages/e2e-tests/package-json-svelte-field/src/main.js
- packages/e2e-tests/prebundle-svelte-deps/src/main.js
- packages/e2e-tests/preprocess-with-vite/src/index.ts
- packages/e2e-tests/resolve-exports-svelte/src/main.js
- packages/e2e-tests/svelte-preprocess/src/main.ts
- packages/e2e-tests/ts-type-import/src/index.ts
- packages/e2e-tests/vitestSetup.ts
- packages/vite-plugin-svelte/src/index.js
- packages/vite-plugin-svelte/src/utils/log.js
- pnpm-lock.yaml
the warning was needed in vite-plugin-svelte 3.x because thats not a prerelease.
4.0.0-next will be in prerelease so breaking changes are expected. Inspector is going to work around the same time we release the first one.
cleaning .vite cache in test projects helped locally to avoid test fails on reruns.
> fix(test): improve stability by removing a log and vite cache

- .changeset/long-suns-happen.md
- packages/vite-plugin-svelte/src/index.js
We were missing this option, meaning Svelte modules that were `.ts` or `.js` were always compiled in prod mode.
> fix: ensure svelte modules correctly run in DEV mode

- .changeset/rare-turkeys-mate.md
- .changeset/strong-cherries-know.md
- packages/vite-plugin-svelte/src/preprocess.js
- packages/vite-plugin-svelte/src/utils/options.js
these 2 patches are good to have in v3 too
> chore: backport fixes

- .npmrc
- package.json
- pnpm-lock.yaml
disable package-manager-strict, only allow postinstall for esbuild
> chore: update pnpm9

- .changeset/shiny-rocks-grow.md
- packages/vite-plugin-svelte/src/preprocess.js
so that svelte-check does not trigger dev-only plugins
> fix(vitePreprocess): default to build config 

- packages/e2e-tests/import-queries/__tests__/import-queries.spec.ts
until svelte5 is more stable in that regard
> test: skip tests that use compiler output snapshots 

- docs/faq.md
As per this issue: https://github.com/sveltejs/vite-plugin-svelte/issues/863 , this PR updates the FAQ section to include information on how to go about using inline URLs.
> Update FAQ to include section about inline asset URLs

- .changeset/healthy-years-battle.md
- .changeset/twenty-walls-watch.md
- packages/vite-plugin-svelte/src/utils/esbuild.js
- packages/vite-plugin-svelte/src/utils/id.js
alternative to #949  
this preserves hmr for dependencies that are in node_modules but excluded from optimizeDeps and also ensures that cssHash function is applied consistently so that it does not break during hydration
> fix: align css hash in prebundling and disable hmr

- .changeset/odd-pens-protect.md
- packages/vite-plugin-svelte/src/utils/esbuild.js
This avoid a compatibility issue if prebundled client code compiled with hmr false hydrates server code compiled with hmr true. Even if it should be identical now that might not be true in the future.
> fix(hmr): ensure consistent use of compilerOptions.hmr during prebundling

- .github/workflows/ci.yml
- .github/workflows/release.yml
- `--prefer-offline` isn't needed
-  pinning changesets/action prevents malicious updates creeping in
- remove `.npmrc` after use to avoid it leaking token
> chore(actions): harden release action and clean up ci

- .changeset/plenty-weeks-battle.md
- packages/vite-plugin-svelte/src/public.d.ts
- packages/vite-plugin-svelte/types/index.d.ts
- packages/vite-plugin-svelte/types/index.d.ts.map
primarily exported so that SvelteKit can forward it in its config type. Endusers should prefer the SvelteConfig or Options.
> fix(types): export PluginOptions

- docs/inspector.md
rendered: https://github.com/sveltejs/vite-plugin-svelte/blob/83d993b9cab6f261bdc3d3f65352733cc2db9bfa/docs/inspector.md
> docs: make inspector docs more scannable

- .changeset/tall-monkeys-shout.md
- docs/inspector.md
- packages/vite-plugin-svelte-inspector/src/options.js
- packages/vite-plugin-svelte-inspector/src/runtime/Inspector.svelte
Why `alt-x`?
It should be 2 key, and usable with one hand. And most importantly not conflict with a lot of other key-combos.
The previous defaults (ctrl-shift or meta-shift) are used in many combos so they accidentally triggered the inspector eg when making a screenshot with meta-shift-3 on mac.
During my testing, `alt-x` did not trigger anything in linux, windows, mac for chrome or firefox, which should cover most users setups for development.
> breaking(options): change default key-combo for svelte-inspector to alt-x

- .changeset/cold-hats-leave.md
- eslint.config.js
- packages/vite-plugin-svelte-inspector/src/runtime/Inspector.svelte
> fix(inspector): use runes and force runes mode

- packages/e2e-tests/css-dev-sourcemap/src/App.svelte
- packages/e2e-tests/svelte-preprocess/__tests__/svelte-preprocess.spec.ts
- packages/e2e-tests/svelte-preprocess/src/lib/multifile/MultiFile.scss
- packages/vite-plugin-svelte/__tests__/preprocess.spec.js
`@import` is deprecated in scss, and we can use `@use` in place instead. This removes the deprecation warnings logged when running the tests and with the vite beta.
> chore: migrate scss import to use

- .changeset/hungry-pans-check.md
- docs/advanced-usage.md
- docs/config.md
- packages/playground/big-component-library-vite-ssr/vite.config.js
- packages/vite-plugin-svelte/src/public.d.ts
- packages/vite-plugin-svelte/src/utils/id.js
- packages/vite-plugin-svelte/types/index.d.ts
hydratable and enableSourcemaps were removed, also values for generate and css have changed.
fixes #1002
> fix: remove references to compiler options no longer available in svelte5

- .github/workflows/ci.yml
- .github/workflows/release.yml
Since node 22 is now on active lts, maybe we should switch to that
> ci: test node 22 lts

- .changeset/swift-dolphins-cheat.md
- packages/vite-plugin-svelte/src/utils/compile.js
Fix for https://github.com/sveltejs/svelte/issues/14384
I just copied the svelte compiler's regex and adjusted the match array index.
Question: is it possible to directly use the regex from the svelte compiler?
> fix: use script lang regex from svelte compiler

- .changeset/eleven-pears-compare.md
- packages/e2e-tests/import-queries/svelte.config.js
- packages/vite-plugin-svelte/src/utils/error.js
- packages/vite-plugin-svelte/src/utils/log.js
- pnpm-lock.yaml
needs to be backported to v-p-s@4 too
> fix: update warning codes for svelte5

- .changeset/eleven-pears-compare.md
- packages/e2e-tests/import-queries/svelte.config.js
- packages/vite-plugin-svelte/src/utils/error.js
- packages/vite-plugin-svelte/src/utils/log.js
- pnpm-lock.yaml
* fix: update warning codes for svelte5
* fix(audit): bump nanoid
* fix: replace css error code detection so that it works for svelte5
* chore: update changeset
(cherry picked from commit e41edff61afe645c2f6b07fa1b3bfd98ec8d806e)
> fix: update warning codes for svelte5 (#1044)

- .changeset/giant-plants-learn.md
- packages/vite-plugin-svelte/src/utils/error.js
Starting a new vite project and selecting svelte-ts template results in an error, because `code` var in error.js is null. Optional chaining resolves this issue.
> Use optional chaining to catch null error codes in error.js

- packages/vite-plugin-svelte-inspector/src/public.d.ts
- packages/vite-plugin-svelte-inspector/types/index.d.ts
The default key combo was changed in #995 but not reflect in TypeScript definitions.
> fix(types): correct default key combo in typing docs

- .changeset/plenty-eyes-talk.md
- packages/e2e-tests/css-treeshake/__tests__/css-treeshake.spec.ts
- packages/e2e-tests/css-treeshake/index.html
- packages/e2e-tests/css-treeshake/package.json
- packages/e2e-tests/css-treeshake/src/A.svelte
- packages/e2e-tests/css-treeshake/src/App.svelte
- packages/e2e-tests/css-treeshake/src/B.svelte
- packages/e2e-tests/css-treeshake/src/C.svelte
- packages/e2e-tests/css-treeshake/src/barrel.js
- packages/e2e-tests/css-treeshake/src/main.js
- packages/e2e-tests/css-treeshake/src/vite-env.d.ts
- packages/e2e-tests/css-treeshake/svelte.config.js
- packages/e2e-tests/css-treeshake/vite.config.js
- packages/vite-plugin-svelte/package.json
- packages/vite-plugin-svelte/src/index.js
- packages/vite-plugin-svelte/src/types/compile.d.ts
- packages/vite-plugin-svelte/src/utils/compile.js
- pnpm-lock.yaml
see https://github.com/vitejs/vite/pull/19418
This allows vite to treeshake unused svelte component css if the component was referenced in a barrel file.
> feat: scope css to js module to allow treeshaking it (requires vite 6.2)

- .changeset/fine-nights-mix.md
- packages/e2e-tests/kit-node/__tests__/kit.spec.ts
- packages/e2e-tests/prebundle-svelte-deps/__tests__/prebundle-svelte-deps.spec.ts
- packages/vite-plugin-svelte/src/utils/constants.js
- packages/vite-plugin-svelte/src/utils/options.js
this avoids a dev server restart when using npm and vite6, see #1067
> fix: optimize "svelte > clsx" by default

- packages/e2e-tests/kit-node/vite.config.js
> chore: remove workaround for older kit version in test

- .changeset/heavy-dots-repeat.md
- .changeset/huge-lamps-greet.md
- .changeset/hungry-phones-prove.md
- .github/workflows/ci.yml
- eslint.config.js
- packages/e2e-tests/_test_dependencies/vite-plugins/index.js
- packages/e2e-tests/kit-node/.gitignore
- packages/e2e-tests/prebundle-svelte-deps/svelte.config.js
- packages/e2e-tests/preprocess-with-vite/__tests__/preprocess-with-vite.spec.ts
- packages/e2e-tests/preprocess-with-vite/package.json
- packages/e2e-tests/preprocess-with-vite/src/App.svelte
- packages/e2e-tests/preprocess-with-vite/src/index.ts
- packages/e2e-tests/preprocess-with-vite/src/tsconfig.json
- packages/e2e-tests/preprocess-with-vite/svelte.config.js
- packages/e2e-tests/scan-deps/__tests__/scan-deps.spec.ts
- packages/e2e-tests/vitestSetup.ts
- packages/vite-plugin-svelte/src/index.js
- packages/vite-plugin-svelte/src/preprocess.js
- packages/vite-plugin-svelte/src/types/compile.d.ts
- packages/vite-plugin-svelte/src/utils/optimizer-plugins.js
- packages/vite-plugin-svelte/src/utils/options.js
- packages/vite-plugin-svelte/types/index.d.ts.map
- pnpm-lock.yaml
fixes #1117 
the goal is that users can swap in npm:rolldown-vite for vite, vite-plugin-svelte detects it and it *just works*
optional:
> feat: experimental rolldown-vite support

- packages/vite-plugin-svelte-inspector/package.json
- packages/vite-plugin-svelte/package.json
avoids odd changesets behavior
maybe we should move the inspector inside vite-plugin-svelte again. it was made  a separate plugin to be able to update it without updating vite-plugin-svelte but that hardly happened and this circular dependency is an annoyance on every major release.
> chore: remove workspace ref from plugins circular dep 

- .changeset/real-cups-scream.md
- packages/e2e-tests/kit-node/__tests__/kit.spec.ts
- packages/e2e-tests/scan-deps/__tests__/scan-deps.spec.ts
- packages/vite-plugin-svelte/src/index.js
and log link to list of known issues.
> fix: allow tests to pass with known rolldown-vite issue

- .changeset/tall-rivers-sleep.md
- packages/vite-plugin-svelte/CHANGELOG.md
because gh does not render nested fancy notes
> chore: change note formatting 

- .changeset/cuddly-bars-clap.md
- packages/vite-plugin-svelte/src/public.d.ts
- packages/vite-plugin-svelte/src/utils/constants.js
- packages/vite-plugin-svelte/src/utils/options.js
- packages/vite-plugin-svelte/src/utils/preprocess.js
- packages/vite-plugin-svelte/types/index.d.ts
- packages/vite-plugin-svelte/types/index.d.ts.map
this allows users to set their logLevel to warn or disable them individually.
> fix: reduce logging for deprecations

- package.json
- packages/e2e-tests/kit-node/__tests__/kit.spec.ts
- pnpm-lock.yaml
this avoids an error in svelte-ecosystem-ci
> chore: bump sveltekit and update test expect

- docs/config.md
Update to v6, add missing options, spelling & wording
> chore: update docs

- README.md
- package.json
and add a way to focus e2e tests from `pnpm test`
> chore: update readme to explain scripts

- .github/workflows/release.yml
use node24 and remove NPM_TOKEN
> update release workfow for oidc publish
