.changeset/flat-books-kick.md
packages/vite-plugin-svelte/src/utils/preprocess.ts

superseeds https://github.com/sveltejs/vite-plugin-svelte/pull/1

feat: reduce number of js updates when editing component css

---

packages/vite-plugin-svelte/src/index.ts

Thank you for such a great plugin 🎉 
It's a really small change.

Add a space after the period in warning message.

---

.changeset/brave-boxes-drive.md
packages/vite-plugin-svelte/src/utils/loadSvelteConfig.ts

see https://github.com/sveltejs/vite-plugin-svelte/issues/29#issuecomment-828218723
cc @dummdidumm

fix: use pathToFileURL to ensure windows compatibility

---

.changeset/yellow-panthers-beg.md
packages/vite-plugin-svelte/package.json
packages/vite-plugin-svelte/src/handle-hot-update.ts
packages/vite-plugin-svelte/src/index.ts
packages/vite-plugin-svelte/src/utils/log.ts
pnpm-lock.yaml

minor improvements to ensure single line logs and less noise.

fix: reduced logging (fixes #42)

---

packages/vite-plugin-svelte/src/utils/options.ts

chore: remove vite config option 

---

packages/vite-plugin-svelte/README.md

see https://github.com/sveltejs/vite-plugin-svelte/issues/86#issuecomment-877099802

docs: add faq to explain hmr [skip ci]

---

.changeset/plenty-pumpkins-buy.md
.changeset/proud-dragons-shout.md
packages/vite-plugin-svelte/package.json
packages/vite-plugin-svelte/src/utils/__tests__/sourcemap.spec.ts
packages/vite-plugin-svelte/src/utils/log.ts
packages/vite-plugin-svelte/src/utils/options.ts
packages/vite-plugin-svelte/src/utils/preprocess.ts
packages/vite-plugin-svelte/src/utils/sourcemap.ts
pnpm-lock.yaml
scripts/jestPerTestSetup.ts

some community provided preprocessors do not return sourcemaps for their transforms which can be a source for errors during hmr.

feat: generate preprocessor sourcemaps

---

package.json
packages/e2e-tests/autoprefixer-browerslist/package.json
packages/e2e-tests/configfile-custom/package.json
packages/e2e-tests/configfile-esm/package.json
packages/e2e-tests/custom-extensions/package.json
packages/e2e-tests/hmr/package.json
packages/e2e-tests/kit-node/package.json
packages/e2e-tests/package-json-svelte-field/package.json
packages/e2e-tests/svelte-preprocess/package.json
packages/e2e-tests/ts-type-import/package.json
packages/e2e-tests/vite-ssr/package.json
packages/playground/big/package.json
packages/playground/kit-demo-app/package.json
packages/playground/optimizedeps-include/package.json
packages/playground/preprocess-with-vite/package.json
packages/playground/windicss/package.json
packages/vite-plugin-svelte/package.json
pnpm-lock.yaml

fix: update dependencies and override tar to fix audit issue

---

.changeset/funny-clocks-drum.md
packages/vite-plugin-svelte/src/utils/options.ts

fixes #138 
see https://github.com/sveltejs/kit/issues/2181

fix: don't add svelte/ssr to optimizeDeps.include (fixes #138)

---

.changeset/nasty-worms-admire.md
packages/vite-plugin-svelte/src/utils/options.ts

auto excluded dependencies also need to be added to ssr.noExternal

fix: add auto-excluded svelte dependencies to ssr.noExternal

---

docs/faq.md

update FAQ entry now that we handle it automatically

docs: update FAQ entry about vite dependency pre-bundling

---

CONTRIBUTING.md
docs/config.md
docs/faq.md

docs: note chromium workaround

---

.changeset/famous-pets-tell.md
packages/vite-plugin-svelte/src/index.ts
packages/vite-plugin-svelte/src/utils/resolve.ts

as discussed in the maintainer's chat

chore: remove package.json export warning

---

.editorconfig
.prettierrc.js
README.md
docs/config.md
docs/faq.md
packages/vite-plugin-svelte/README.md

improves rendering in github ui, see https://github.com/sveltejs/kit/pull/4749

chore: switch indentation to spaces in README.md

---

.changeset/witty-eggs-allow.md

actual fix commit is part of #342   
https://github.com/sveltejs/vite-plugin-svelte/pull/342/commits/6a7b7c4aac424f9736d1faec74b4adfe196acc0f

chore: add missing changeset for bugfix in version updates PR

---

.gitignore
package.json
packages/e2e-tests/_test_dependencies/svelte-hybrid/package.json
packages/e2e-tests/autoprefixer-browerslist/package.json
packages/e2e-tests/kit-node/package.json
packages/e2e-tests/package.json
packages/e2e-tests/preprocess-with-vite/package.json
packages/e2e-tests/svelte-preprocess/package.json
packages/e2e-tests/ts-type-import/package.json
packages/playground/big-component-library/package.json
packages/vite-plugin-svelte/package.json
pnpm-lock.yaml

regenerated lockfile, adapted settings for tsup and pnpm peer deps

chore(deps): major updates tsup6, typescript 4.7, vitest 0.13, 

---

.changeset/tidy-months-explode.md
.changeset/two-rice-end.md
packages/vite-plugin-svelte/src/index.ts
packages/vite-plugin-svelte/src/utils/load-svelte-config.ts

Closes https://github.com/sveltejs/vite-plugin-svelte/issues/348

Use mtime as timestamp when loading config file

---

packages/vite-plugin-svelte/src/handle-hot-update.ts

docs: remove sapper-studio ref

---

.changeset/polite-mails-press.md
packages/e2e-tests/inspector-kit/__tests__/inspector.kit.spec.ts
packages/e2e-tests/inspector-vite/__tests__/inspector.vite.spec.ts
packages/vite-plugin-svelte/src/ui/inspector/Inspector.svelte

fix(svelte-inspector): prevent info-bubble select

---

.github/workflows/ci.yml
.github/workflows/release.yml
packages/e2e-tests/vitestGlobalSetup.ts
packages/e2e-tests/vitestSetup.ts

- apply permission hardening, 
- use downloaded chromium instead of platform browser to avoid issues
- update chromium flags and dep install for local testing

ci: improve workflow

---

.github/workflows/ci.yml
package.json
packages/e2e-tests/hmr/__tests__/hmr.spec.ts
packages/e2e-tests/kit-node/__tests__/kit.spec.ts
packages/e2e-tests/testUtils.ts
packages/e2e-tests/vitestSetup.ts
pnpm-lock.yaml

and refactor tests to work with its changed behavior
introduced a new helper to wait for server restart, improved some helpers

chore: unpin playwright 

---

package.json
packages/e2e-tests/_test_dependencies/svelte-api-only/package.json
packages/e2e-tests/autoprefixer-browerslist/package.json
packages/e2e-tests/configfile-custom/package.json
packages/e2e-tests/configfile-esm/package.json
packages/e2e-tests/css-none/package.json
packages/e2e-tests/custom-extensions/package.json
packages/e2e-tests/env/package.json
packages/e2e-tests/hmr/package.json
packages/e2e-tests/inspector-kit/package.json
packages/e2e-tests/inspector-vite/package.json
packages/e2e-tests/kit-node/package.json
packages/e2e-tests/package-json-svelte-field/package.json
packages/e2e-tests/prebundle-svelte-deps/package.json
packages/e2e-tests/preprocess-with-vite/package.json
packages/e2e-tests/svelte-preprocess/package.json
packages/e2e-tests/ts-type-import/package.json
packages/e2e-tests/vite-ssr-esm/package.json
packages/e2e-tests/vite-ssr/package.json
packages/playground/big-component-library/package.json
packages/playground/big/package.json
packages/playground/kit-demo-app/package.json
packages/playground/optimizedeps-include/package.json
packages/playground/windicss/package.json
packages/vite-plugin-svelte/package.json
pnpm-lock.yaml

not sure where i lost it but renovate might refrain from bumping if it isn't there so here it goes

fix: restore caret for svelte version

---

.changeset/short-clouds-build.md
packages/vite-plugin-svelte/src/index.ts

as vite 4 had to revert the change we needed to make that step

feat!: reintroduce custom svelte/ssr resolve 

---

packages/e2e-tests/hmr/__tests__/hmr.spec.ts
packages/e2e-tests/package-json-svelte-field/package.json
packages/e2e-tests/prebundle-svelte-deps/__tests__/prebundle-svelte-deps.spec.ts
packages/e2e-tests/testUtils.ts
pnpm-lock.yaml

Hopefully this fixes Vite 4.3 ecosystem-ci

test: try fix ci with vite 4.3

---

.changeset/fluffy-dancers-impress.md
packages/vite-plugin-svelte/src/utils/resolve.ts

fix(resolve): normalize path returned from svelte field resolve

---

.changeset/sweet-fireants-attend.md
packages/vite-plugin-svelte/src/index.ts

fix(build): watch preprocessor dependencies during build --watch

---

docs/inspector.md

Mention editors for inspector

---

.changeset/config.json
.github/ISSUE_TEMPLATE/bug_report.yml
.github/renovate.json5
.prettierrc.js
package.json
packages/e2e-tests/_test_dependencies/cjs-and-esm/index.cjs
packages/e2e-tests/_test_dependencies/cjs-and-esm/index.mjs
packages/e2e-tests/_test_dependencies/cjs-and-esm/package.json
packages/e2e-tests/_test_dependencies/esm-only/package.json
packages/e2e-tests/_test_dependencies/svelte-exports-simple/package.json
packages/e2e-tests/configfile-custom/svelte.config.cjs
packages/e2e-tests/configfile-custom/svelte.config.custom.cjs
packages/e2e-tests/configfile-custom/svelte.config.custom.mjs
packages/e2e-tests/inspector-vite/jsconfig.json
packages/e2e-tests/svelte-preprocess/tsconfig.json
packages/e2e-tests/ts-type-import/tsconfig.json
packages/e2e-tests/tsconfig.json
packages/playground/big-component-library-kit/package.json
packages/playground/big-component-library-vite-ssr/jsconfig.json
packages/playground/big-component-library/jsconfig.json
packages/playground/kit-demo-app/package.json
packages/playground/optimizedeps-include/jsconfig.json
packages/vite-plugin-svelte-inspector/package.json
packages/vite-plugin-svelte-inspector/tsconfig.json
packages/vite-plugin-svelte/tsconfig.json

can we add this to blame ignore here or do we have to merge into main first?

chore: enable prettier for json and reformat

---

.eslintrc.js
package.json
packages/vite-plugin-svelte/package.json
pnpm-lock.yaml

And also migrate `eslint-plugin-svelte3` to `eslint-plugin-svelte`

chore: remove unused deps

---

packages/e2e-tests/vite-ssr-esm/package.json
packages/e2e-tests/vite-ssr-esm/server.js
packages/playground/big-component-library-vite-ssr/package.json
packages/playground/big-component-library-vite-ssr/server.js

see https://github.com/vitejs/vite/pull/14230

test(vite-ssr): set manifest location per vite5

---

.eslintrc.cjs
.prettierrc.js
package.json
packages/vite-plugin-svelte/src/utils/load-svelte-config.js

Had to also tweak some strange eslint linting with this change.

chore: use type module in root

---

package.json
packages/e2e-tests/package.json
pnpm-lock.yaml

vitest 1.0, dedupe and bump css-tools so dependabot shuts up

chore(deps): vitest 1.0

---

docs/config.md

This option isn't experimental anymore.

docs: fix usage example for dynamicCompileOptions

---

.changeset/slow-eagles-unite.md
packages/vite-plugin-svelte/src/utils/id.js

fix: only apply infix filter to basename

---

.github/workflows/ci.yml
.github/workflows/release.yml

chore: update v3 actions

---

docs/config.md

As discussed here:
https://github.com/sveltejs/vite-plugin-svelte/issues/1016

Update config.md to include link to ModuleCompileOptions

---

packages/e2e-tests/import-queries/__tests__/__snapshots__/svelte-5/direct-css.txt
packages/e2e-tests/import-queries/__tests__/__snapshots__/svelte-5/direct-js.txt
packages/e2e-tests/import-queries/__tests__/__snapshots__/svelte-5/ssr-custom-element.txt
packages/e2e-tests/import-queries/__tests__/__snapshots__/svelte-5/ssr-raw.txt
packages/e2e-tests/import-queries/__tests__/__snapshots__/svelte-5/ssr-script.txt
packages/e2e-tests/import-queries/__tests__/import-queries.spec.ts
packages/e2e-tests/inspector-kit/__tests__/inspector.kit.spec.ts
packages/e2e-tests/inspector-vite/__tests__/inspector.vite.spec.ts

Looks like more can be unskipped and passing now

chore: unskip tests

---

.changeset/poor-apples-leave.md
.changeset/pre.json
package.json
packages/vite-plugin-svelte-inspector/package.json
packages/vite-plugin-svelte/package.json
pnpm-lock.yaml

release vps5

---

package.json
packages/e2e-tests/_test_dependencies/svelte-api-only/package.json
packages/e2e-tests/autoprefixer-browerslist/package.json
packages/e2e-tests/configfile-custom/package.json
packages/e2e-tests/configfile-esm/package.json
packages/e2e-tests/css-dev-sourcemap/package.json
packages/e2e-tests/css-treeshake/package.json
packages/e2e-tests/custom-extensions/package.json
packages/e2e-tests/dynamic-compile-options/package.json
packages/e2e-tests/env/package.json
packages/e2e-tests/hmr/package.json
packages/e2e-tests/import-queries/package.json
packages/e2e-tests/inspector-kit/package.json
packages/e2e-tests/inspector-vite/package.json
packages/e2e-tests/kit-node/package.json
packages/e2e-tests/package-json-svelte-field/package.json
packages/e2e-tests/prebundle-svelte-deps/package.json
packages/e2e-tests/preprocess-with-vite/package.json
packages/e2e-tests/resolve-exports-svelte/package.json
packages/e2e-tests/scan-deps/package.json
packages/e2e-tests/svelte-preprocess/package.json
packages/e2e-tests/ts-type-import/package.json
packages/e2e-tests/vite-ssr-esm/package.json
packages/e2e-tests/vite-ssr-esm/server.js
packages/vite-plugin-svelte-inspector/package.json
packages/vite-plugin-svelte/package.json
pnpm-lock.yaml

update remaining deps and replace express/serve-static with polka/sirv

---

.github/ISSUE_TEMPLATE/bug_report.yml

docs: clarify that reproductions must be public and minimal

---

.changeset/major-berries-flow.md
packages/vite-plugin-svelte/src/public.d.ts
packages/vite-plugin-svelte/types/index.d.ts

fix(types): update urls to PreprocessorGroup and CompileOptions docs

---

.npmrc
pnpm-workspace.yaml

because next npm major would error

chore: move pnpm settings from .npmrc to pnpm-workspace.yaml
